/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ccsPackage;

/**
 *
 * @author Alyph
 */
public class FrameMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        initComponents();
        setExtendedState(FrameMenu.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ButtonCompra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ButtomRelatorio = new javax.swing.JButton();
        ButtomSair = new javax.swing.JButton();
        ButtomVenda = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        menuItemCompra = new javax.swing.JMenuItem();
        menuItemVenda = new javax.swing.JMenuItem();
        menuItemRelatorio = new javax.swing.JMenuItem();
        menuOpcoes = new javax.swing.JMenu();
        opcoesItemCreditos = new javax.swing.JMenuItem();
        opcoesItemAjuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        setLocation(new java.awt.Point(500, 350));
        setLocationByPlatform(true);
        setMaximumSize(null);
        setMinimumSize(null);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Central Control System - CCS");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ccsImagens/imgRelatorio.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(321, 286));
        jLabel1.setMinimumSize(new java.awt.Dimension(321, 286));
        jLabel1.setName("ImgCompra"); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(321, 286));

        ButtonCompra.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ButtonCompra.setText("Compra");
        ButtonCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCompraMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alyph\\OneDrive\\Documentos\\NetBeansProjects\\CentralControlSystem\\src\\ccsImagens\\imgCompra.png")); // NOI18N
        jLabel3.setName("ImgCompra"); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ccsImagens/imgVenda.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setName("ImgCompra"); // NOI18N

        ButtomRelatorio.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ButtomRelatorio.setText("Relatório");
        ButtomRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtomRelatorioMouseClicked(evt);
            }
        });

        ButtomSair.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ButtomSair.setText("Sair");
        ButtomSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtomSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtomSairMouseClicked(evt);
            }
        });

        ButtomVenda.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ButtomVenda.setText("Venda");
        ButtomVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtomVendaMouseClicked(evt);
            }
        });

        menuBar.setBorder(null);
        menuBar.setForeground(new java.awt.Color(240, 240, 240));
        menuBar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        menuMenu.setText("Menu");
        menuMenu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        menuItemCompra.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        menuItemCompra.setText("Compra");
        menuItemCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemCompraMouseClicked(evt);
            }
        });
        menuMenu.add(menuItemCompra);

        menuItemVenda.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        menuItemVenda.setText("Venda");
        menuItemVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemVendaMouseClicked(evt);
            }
        });
        menuItemVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVendaActionPerformed(evt);
            }
        });
        menuMenu.add(menuItemVenda);

        menuItemRelatorio.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        menuItemRelatorio.setText("Relatório");
        menuItemRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemRelatorioMouseClicked(evt);
            }
        });
        menuMenu.add(menuItemRelatorio);

        menuBar.add(menuMenu);

        menuOpcoes.setText("Opções");
        menuOpcoes.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        opcoesItemCreditos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        opcoesItemCreditos.setText("Créditos");
        opcoesItemCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcoesItemCreditosMouseClicked(evt);
            }
        });
        opcoesItemCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcoesItemCreditosActionPerformed(evt);
            }
        });
        menuOpcoes.add(opcoesItemCreditos);

        opcoesItemAjuda.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        opcoesItemAjuda.setText("Ajuda");
        opcoesItemAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcoesItemAjudaMouseClicked(evt);
            }
        });
        menuOpcoes.add(opcoesItemAjuda);

        menuBar.add(menuOpcoes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtomVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtomSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                            .addComponent(ButtomRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ButtonCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtomRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ButtomVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(ButtomSair, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jLabel2.getAccessibleContext().setAccessibleName("labelMenuNome");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemVendaActionPerformed

    private void ButtomSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtomSairMouseClicked
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ButtomSairMouseClicked

    private void ButtonCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCompraMouseClicked
        FrameCompra frameCompra = new FrameCompra();
        frameCompra.setVisible(true);        
    }//GEN-LAST:event_ButtonCompraMouseClicked

    private void ButtomVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtomVendaMouseClicked
        FrameVenda frameVenda = new FrameVenda();
        frameVenda.setVisible(true);
    }//GEN-LAST:event_ButtomVendaMouseClicked

    private void ButtomRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtomRelatorioMouseClicked
        FrameRelatorio frameRelatorio = new FrameRelatorio();
        frameRelatorio.setVisible(true);
    }//GEN-LAST:event_ButtomRelatorioMouseClicked

    private void menuItemCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemCompraMouseClicked
        FrameCompra frameCompra = new FrameCompra();
        frameCompra.setVisible(true); 
    }//GEN-LAST:event_menuItemCompraMouseClicked

    private void menuItemVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemVendaMouseClicked
        FrameVenda frameVenda = new FrameVenda();
        frameVenda.setVisible(true);
    }//GEN-LAST:event_menuItemVendaMouseClicked

    private void menuItemRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemRelatorioMouseClicked
        FrameRelatorio frameRelatorio = new FrameRelatorio();
        frameRelatorio.setVisible(true);
    }//GEN-LAST:event_menuItemRelatorioMouseClicked

    private void opcoesItemCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcoesItemCreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcoesItemCreditosActionPerformed

    private void opcoesItemCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcoesItemCreditosMouseClicked
        FrameCreditos frameCreditos = new FrameCreditos();
        frameCreditos.setVisible(true);
    }//GEN-LAST:event_opcoesItemCreditosMouseClicked

    private void opcoesItemAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcoesItemAjudaMouseClicked
        FrameAjuda frameAjuda = new FrameAjuda();
        frameAjuda.setVisible(true);
    }//GEN-LAST:event_opcoesItemAjudaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenu().setVisible(true);
                
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtomRelatorio;
    private javax.swing.JButton ButtomSair;
    private javax.swing.JButton ButtomVenda;
    private javax.swing.JButton ButtonCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemCompra;
    private javax.swing.JMenuItem menuItemRelatorio;
    private javax.swing.JMenuItem menuItemVenda;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenu menuOpcoes;
    private javax.swing.JMenuItem opcoesItemAjuda;
    private javax.swing.JMenuItem opcoesItemCreditos;
    // End of variables declaration//GEN-END:variables
}
