/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ccsPackage;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Alyph
 */
public class FrameCompra extends javax.swing.JDialog {

    /**
     * Creates new form FrameCompra
     */
    public FrameCompra() {
        initComponents();
    
        this.setModal(true); 
        this.setIconImage(new ImageIcon("C:\\Users\\Alyph\\OneDrive\\Documentos\\NetBeansProjects\\CentralControlSystem\\src\\ccsImagens\\Icons\\iconCompra.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        buttonFechar = new javax.swing.JButton();
        labelCompra = new javax.swing.JLabel();
        labelCompraNumeroDaOrdem = new javax.swing.JLabel();
        labelCompraNomeProduto = new javax.swing.JLabel();
        labelCompraQuantidade = new javax.swing.JLabel();
        labelCompraFornecedor = new javax.swing.JLabel();
        labelCompraValor = new javax.swing.JLabel();
        labelCompraCPF = new javax.swing.JLabel();
        labelCompraCodigo = new javax.swing.JLabel();
        labelCompraObservacoes = new javax.swing.JLabel();
        labelCompraData = new javax.swing.JLabel();
        buttonSalvar = new javax.swing.JButton();
        buttonLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaObservacoesCompra = new javax.swing.JTextArea();
        textDataCompra = new javax.swing.JFormattedTextField();
        textQtdCompra = new javax.swing.JFormattedTextField();
        textValorCompra = new javax.swing.JFormattedTextField();
        textCPFCompra = new javax.swing.JFormattedTextField();
        textNomeProduto = new javax.swing.JTextField();
        textFornecedor = new javax.swing.JTextField();
        textNumeroOrdemCompra = new javax.swing.JTextField();
        textCodigoCompra = new javax.swing.JTextField();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Fornecedor:");

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Central Control System - Compra");
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        buttonFechar.setText("Fechar");
        buttonFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonFecharMouseClicked(evt);
            }
        });
        buttonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFecharActionPerformed(evt);
            }
        });

        labelCompra.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 36)); // NOI18N
        labelCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCompra.setText("Compra");

        labelCompraNumeroDaOrdem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelCompraNumeroDaOrdem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCompraNumeroDaOrdem.setText("Número da Ordem:");

        labelCompraNomeProduto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelCompraNomeProduto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCompraNomeProduto.setText("Nome do Produto:");

        labelCompraQuantidade.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelCompraQuantidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCompraQuantidade.setText("Quantidade:");

        labelCompraFornecedor.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelCompraFornecedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCompraFornecedor.setText("Fornecedor:");

        labelCompraValor.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelCompraValor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCompraValor.setText("Valor:");

        labelCompraCPF.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelCompraCPF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCompraCPF.setText("CPF/CNPJ:");

        labelCompraCodigo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelCompraCodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCompraCodigo.setText("Código do Produto:");

        labelCompraObservacoes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelCompraObservacoes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCompraObservacoes.setText("Observações:");

        labelCompraData.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelCompraData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCompraData.setText("Data da Ordem:");

        buttonSalvar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        buttonSalvar.setText("Salvar");
        buttonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSalvarMouseClicked(evt);
            }
        });
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonLimpar.setText("Limpar");
        buttonLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLimparMouseClicked(evt);
            }
        });
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        textAreaObservacoesCompra.setColumns(5);
        textAreaObservacoesCompra.setRows(5);
        jScrollPane1.setViewportView(textAreaObservacoesCompra);

        try {
            textDataCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textDataCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDataCompraActionPerformed(evt);
            }
        });

        textQtdCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        textQtdCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQtdCompraActionPerformed(evt);
            }
        });

        textValorCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        textValorCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textValorCompraActionPerformed(evt);
            }
        });

        try {
            textCPFCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textCPFCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCPFCompraActionPerformed(evt);
            }
        });

        textNumeroOrdemCompra.setPreferredSize(new java.awt.Dimension(6, 22));

        textCodigoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodigoCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelCompraData, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(textDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(230, 230, 230))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCompraNumeroDaOrdem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelCompraCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelCompraQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCompraObservacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelCompraCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelCompraFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelCompraValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelCompraNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonFechar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textQtdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(textCPFCompra, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(buttonLimpar)
                                            .addGap(18, 18, 18)
                                            .addComponent(buttonSalvar))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                                    .addGap(30, 30, 30)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(textNumeroOrdemCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(200, 200, 200)))
                            .addComponent(textCodigoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompraNumeroDaOrdem)
                    .addComponent(textNumeroOrdemCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompraData)
                    .addComponent(textDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompraCodigo)
                    .addComponent(textCodigoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompraQuantidade)
                    .addComponent(textQtdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompraNomeProduto)
                    .addComponent(textNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompraValor)
                    .addComponent(textValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompraFornecedor)
                    .addComponent(textFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompraCPF)
                    .addComponent(textCPFCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCompraObservacoes)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFechar)
                    .addComponent(buttonSalvar)
                    .addComponent(buttonLimpar))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonFecharActionPerformed

    private void buttonFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFecharMouseClicked
        
        
        int opcao = JOptionPane.showConfirmDialog(null,"Realmente deseja sair?","Central Control System - Compra", JOptionPane.YES_NO_CANCEL_OPTION);
      
        if (opcao == JOptionPane.YES_OPTION) {
            this.dispose();
        } 
        else if (opcao == JOptionPane.NO_OPTION){
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            
        }
        
    }//GEN-LAST:event_buttonFecharMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void buttonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSalvarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSalvarMouseClicked

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void buttonLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLimparMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLimparMouseClicked

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed

      textNumeroOrdemCompra.setText(null);
      textDataCompra.setText(null);
      textCodigoCompra.setText(null);
      textQtdCompra.setText(null);
      textNomeProduto.setText(null);
      textValorCompra.setText(null);
      textFornecedor.setText(null);
      textCPFCompra.setText(null);
      textAreaObservacoesCompra.setText(null);
  
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void textDataCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDataCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDataCompraActionPerformed

    private void textQtdCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQtdCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQtdCompraActionPerformed

    private void textValorCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textValorCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textValorCompraActionPerformed

    private void textCPFCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCPFCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCPFCompraActionPerformed

    private void textCodigoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodigoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodigoCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCompra().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFechar;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel labelCompra;
    private javax.swing.JLabel labelCompraCPF;
    private javax.swing.JLabel labelCompraCodigo;
    private javax.swing.JLabel labelCompraData;
    private javax.swing.JLabel labelCompraFornecedor;
    private javax.swing.JLabel labelCompraNomeProduto;
    private javax.swing.JLabel labelCompraNumeroDaOrdem;
    private javax.swing.JLabel labelCompraObservacoes;
    private javax.swing.JLabel labelCompraQuantidade;
    private javax.swing.JLabel labelCompraValor;
    private javax.swing.JTextArea textAreaObservacoesCompra;
    private javax.swing.JFormattedTextField textCPFCompra;
    private javax.swing.JTextField textCodigoCompra;
    private javax.swing.JFormattedTextField textDataCompra;
    private javax.swing.JTextField textFornecedor;
    private javax.swing.JTextField textNomeProduto;
    private javax.swing.JTextField textNumeroOrdemCompra;
    private javax.swing.JFormattedTextField textQtdCompra;
    private javax.swing.JFormattedTextField textValorCompra;
    // End of variables declaration//GEN-END:variables
}
